version: '3'

services:
  node: &app_base
    image: node:11.14.0-alpine
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www # ./srcをコンテナ内の/var/wwwにマウントする
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    restart: always # エラーなどでコンテナが落ちた際に自動で再起動してくれる

  workspace:
    <<: *app_base
    ports:
      - "127.0.0.1:3000:3000" # localhost:3000にポートをマッピングする
    command: yarn dev
